name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: './perplexity-ask/pnpm-lock.yaml'
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        working-directory: ./perplexity-ask
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: ./perplexity-ask
        run: pnpm run build

      - name: Publish to npm
        working-directory: ./perplexity-ask
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: context.ref.replace('refs/tags/', ''),
              name: `Release ${context.ref.replace('refs/tags/', '')}`,
              body: `## 🚀 Enhanced MCP Server v0.3.0\n\n### Major Features\n- Complete Perplexity API parameter support\n- Advanced search and reasoning controls\n- Enhanced safety and error handling\n- Developer-focused optimizations\n\n### Bug Fixes\n- Fixed image URL undefined display\n- Improved API response validation\n- Enhanced error messages\n\nSee [CLAUDE.md](https://github.com/${context.repo.owner}/${context.repo.repo}/blob/main/CLAUDE.md) for comprehensive usage guide.`,
              draft: false,
              prerelease: false
            });
            console.log(`Created release: ${release.html_url}`) 